### ISSUE TITLE
run with GPU

### ISSUE THREAD

**Issue by Lesnikovsok** [sonnguyen129/Trafic-Management-System#1]
Hi,

Im only getting 1 fps with rtsp feed and its running with cpu.Any way to run dashboard.py with GPU?

thank you.

**Comment by sonnguyen129** [comment]
Hi @Lesnikovsok,
I have set the whole model in GPU mode from the beginning. Please recheck these 2 parts below.

https://github.com/sonnguyen129/Traffic-Flow-Analysis/blob/ab78191e3259c6da3ccb9704bc4121e4f9b59d55/detector.py#L18-L21

https://github.com/sonnguyen129/Traffic-Flow-Analysis/blob/ab78191e3259c6da3ccb9704bc4121e4f9b59d55/mainTracker.py#L201-L210

Then follow the ipynb file.

**Comment by Lesnikovsok** [comment]
I edited detector.py to run only on GPU. And find that my torch installation was not compiled with CUDA enabled. 
Reinstalled Torch with CUDA enabled and now everything works fine (getting 23-25 frames).
Thank you.

**Comment by sonnguyen129** [comment]
Great. I will close this issue. If you have any questions in the future, feel free to create issues.
